# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Start the environment
        run: npm run start

      - name: Wait for services to be ready
        run: npm run cli wait-for mysql:3306

      - name: Make root project directory writable by Docker user
        run: docker compose run --remove-orphans wp chown -R www-data /var/www/html

      - name: Install dependencies
        run: npm run cli -- composer install

      - name: Setup WordPress
        run: npm run wp -- core install

      # TODO: replace with an actual test
      - name: List plugins
        run: npm run wp -- plugin list  
      